// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: compute/v1/compute.proto

package computev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RunServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Image         string                 `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	EnvVars       map[string]string      `protobuf:"bytes,3,rep,name=env_vars,json=envVars,proto3" json:"env_vars,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunServiceRequest) Reset() {
	*x = RunServiceRequest{}
	mi := &file_compute_v1_compute_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunServiceRequest) ProtoMessage() {}

func (x *RunServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_compute_v1_compute_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunServiceRequest.ProtoReflect.Descriptor instead.
func (*RunServiceRequest) Descriptor() ([]byte, []int) {
	return file_compute_v1_compute_proto_rawDescGZIP(), []int{0}
}

func (x *RunServiceRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *RunServiceRequest) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *RunServiceRequest) GetEnvVars() map[string]string {
	if x != nil {
		return x.EnvVars
	}
	return nil
}

type RunServiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EndpointUrl   string                 `protobuf:"bytes,1,opt,name=endpoint_url,json=endpointUrl,proto3" json:"endpoint_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunServiceResponse) Reset() {
	*x = RunServiceResponse{}
	mi := &file_compute_v1_compute_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunServiceResponse) ProtoMessage() {}

func (x *RunServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_compute_v1_compute_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunServiceResponse.ProtoReflect.Descriptor instead.
func (*RunServiceResponse) Descriptor() ([]byte, []int) {
	return file_compute_v1_compute_proto_rawDescGZIP(), []int{1}
}

func (x *RunServiceResponse) GetEndpointUrl() string {
	if x != nil {
		return x.EndpointUrl
	}
	return ""
}

type TriggerFunctionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FunctionName  string                 `protobuf:"bytes,1,opt,name=function_name,json=functionName,proto3" json:"function_name,omitempty"`
	Payload       string                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerFunctionRequest) Reset() {
	*x = TriggerFunctionRequest{}
	mi := &file_compute_v1_compute_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerFunctionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerFunctionRequest) ProtoMessage() {}

func (x *TriggerFunctionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_compute_v1_compute_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerFunctionRequest.ProtoReflect.Descriptor instead.
func (*TriggerFunctionRequest) Descriptor() ([]byte, []int) {
	return file_compute_v1_compute_proto_rawDescGZIP(), []int{2}
}

func (x *TriggerFunctionRequest) GetFunctionName() string {
	if x != nil {
		return x.FunctionName
	}
	return ""
}

func (x *TriggerFunctionRequest) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

type TriggerFunctionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerFunctionResponse) Reset() {
	*x = TriggerFunctionResponse{}
	mi := &file_compute_v1_compute_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerFunctionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerFunctionResponse) ProtoMessage() {}

func (x *TriggerFunctionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_compute_v1_compute_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerFunctionResponse.ProtoReflect.Descriptor instead.
func (*TriggerFunctionResponse) Descriptor() ([]byte, []int) {
	return file_compute_v1_compute_proto_rawDescGZIP(), []int{3}
}

func (x *TriggerFunctionResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

var File_compute_v1_compute_proto protoreflect.FileDescriptor

const file_compute_v1_compute_proto_rawDesc = "" +
	"\n" +
	"\x18compute/v1/compute.proto\x12\n" +
	"compute.v1\"\xcf\x01\n" +
	"\x11RunServiceRequest\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12\x14\n" +
	"\x05image\x18\x02 \x01(\tR\x05image\x12E\n" +
	"\benv_vars\x18\x03 \x03(\v2*.compute.v1.RunServiceRequest.EnvVarsEntryR\aenvVars\x1a:\n" +
	"\fEnvVarsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"7\n" +
	"\x12RunServiceResponse\x12!\n" +
	"\fendpoint_url\x18\x01 \x01(\tR\vendpointUrl\"W\n" +
	"\x16TriggerFunctionRequest\x12#\n" +
	"\rfunction_name\x18\x01 \x01(\tR\ffunctionName\x12\x18\n" +
	"\apayload\x18\x02 \x01(\tR\apayload\"1\n" +
	"\x17TriggerFunctionResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result2\xb9\x01\n" +
	"\x0eComputeService\x12K\n" +
	"\n" +
	"RunService\x12\x1d.compute.v1.RunServiceRequest\x1a\x1e.compute.v1.RunServiceResponse\x12Z\n" +
	"\x0fTriggerFunction\x12\".compute.v1.TriggerFunctionRequest\x1a#.compute.v1.TriggerFunctionResponseBhZfOlympusGCP-Compute/40000-Communication-Contracts/430-Protocol-Definitions/000-gen/compute/v1;computev1b\x06proto3"

var (
	file_compute_v1_compute_proto_rawDescOnce sync.Once
	file_compute_v1_compute_proto_rawDescData []byte
)

func file_compute_v1_compute_proto_rawDescGZIP() []byte {
	file_compute_v1_compute_proto_rawDescOnce.Do(func() {
		file_compute_v1_compute_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_compute_v1_compute_proto_rawDesc), len(file_compute_v1_compute_proto_rawDesc)))
	})
	return file_compute_v1_compute_proto_rawDescData
}

var file_compute_v1_compute_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_compute_v1_compute_proto_goTypes = []any{
	(*RunServiceRequest)(nil),       // 0: compute.v1.RunServiceRequest
	(*RunServiceResponse)(nil),      // 1: compute.v1.RunServiceResponse
	(*TriggerFunctionRequest)(nil),  // 2: compute.v1.TriggerFunctionRequest
	(*TriggerFunctionResponse)(nil), // 3: compute.v1.TriggerFunctionResponse
	nil,                             // 4: compute.v1.RunServiceRequest.EnvVarsEntry
}
var file_compute_v1_compute_proto_depIdxs = []int32{
	4, // 0: compute.v1.RunServiceRequest.env_vars:type_name -> compute.v1.RunServiceRequest.EnvVarsEntry
	0, // 1: compute.v1.ComputeService.RunService:input_type -> compute.v1.RunServiceRequest
	2, // 2: compute.v1.ComputeService.TriggerFunction:input_type -> compute.v1.TriggerFunctionRequest
	1, // 3: compute.v1.ComputeService.RunService:output_type -> compute.v1.RunServiceResponse
	3, // 4: compute.v1.ComputeService.TriggerFunction:output_type -> compute.v1.TriggerFunctionResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_compute_v1_compute_proto_init() }
func file_compute_v1_compute_proto_init() {
	if File_compute_v1_compute_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_compute_v1_compute_proto_rawDesc), len(file_compute_v1_compute_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_compute_v1_compute_proto_goTypes,
		DependencyIndexes: file_compute_v1_compute_proto_depIdxs,
		MessageInfos:      file_compute_v1_compute_proto_msgTypes,
	}.Build()
	File_compute_v1_compute_proto = out.File
	file_compute_v1_compute_proto_goTypes = nil
	file_compute_v1_compute_proto_depIdxs = nil
}
