// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: compute/v1/compute.proto

package computev1connect

import (
	v1 "OlympusGCP-Compute/40000-Communication-Contracts/430-Protocol-Definitions/000-gen/compute/v1"
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ComputeServiceName is the fully-qualified name of the ComputeService service.
	ComputeServiceName = "compute.v1.ComputeService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ComputeServiceRunServiceProcedure is the fully-qualified name of the ComputeService's RunService
	// RPC.
	ComputeServiceRunServiceProcedure = "/compute.v1.ComputeService/RunService"
	// ComputeServiceTriggerFunctionProcedure is the fully-qualified name of the ComputeService's
	// TriggerFunction RPC.
	ComputeServiceTriggerFunctionProcedure = "/compute.v1.ComputeService/TriggerFunction"
	// ComputeServiceCheckHealthProcedure is the fully-qualified name of the ComputeService's
	// CheckHealth RPC.
	ComputeServiceCheckHealthProcedure = "/compute.v1.ComputeService/CheckHealth"
)

// ComputeServiceClient is a client for the compute.v1.ComputeService service.
type ComputeServiceClient interface {
	RunService(context.Context, *connect.Request[v1.RunServiceRequest]) (*connect.Response[v1.RunServiceResponse], error)
	TriggerFunction(context.Context, *connect.Request[v1.TriggerFunctionRequest]) (*connect.Response[v1.TriggerFunctionResponse], error)
	CheckHealth(context.Context, *connect.Request[v1.CheckHealthRequest]) (*connect.Response[v1.CheckHealthResponse], error)
}

// NewComputeServiceClient constructs a client for the compute.v1.ComputeService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewComputeServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ComputeServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	computeServiceMethods := v1.File_compute_v1_compute_proto.Services().ByName("ComputeService").Methods()
	return &computeServiceClient{
		runService: connect.NewClient[v1.RunServiceRequest, v1.RunServiceResponse](
			httpClient,
			baseURL+ComputeServiceRunServiceProcedure,
			connect.WithSchema(computeServiceMethods.ByName("RunService")),
			connect.WithClientOptions(opts...),
		),
		triggerFunction: connect.NewClient[v1.TriggerFunctionRequest, v1.TriggerFunctionResponse](
			httpClient,
			baseURL+ComputeServiceTriggerFunctionProcedure,
			connect.WithSchema(computeServiceMethods.ByName("TriggerFunction")),
			connect.WithClientOptions(opts...),
		),
		checkHealth: connect.NewClient[v1.CheckHealthRequest, v1.CheckHealthResponse](
			httpClient,
			baseURL+ComputeServiceCheckHealthProcedure,
			connect.WithSchema(computeServiceMethods.ByName("CheckHealth")),
			connect.WithClientOptions(opts...),
		),
	}
}

// computeServiceClient implements ComputeServiceClient.
type computeServiceClient struct {
	runService      *connect.Client[v1.RunServiceRequest, v1.RunServiceResponse]
	triggerFunction *connect.Client[v1.TriggerFunctionRequest, v1.TriggerFunctionResponse]
	checkHealth     *connect.Client[v1.CheckHealthRequest, v1.CheckHealthResponse]
}

// RunService calls compute.v1.ComputeService.RunService.
func (c *computeServiceClient) RunService(ctx context.Context, req *connect.Request[v1.RunServiceRequest]) (*connect.Response[v1.RunServiceResponse], error) {
	return c.runService.CallUnary(ctx, req)
}

// TriggerFunction calls compute.v1.ComputeService.TriggerFunction.
func (c *computeServiceClient) TriggerFunction(ctx context.Context, req *connect.Request[v1.TriggerFunctionRequest]) (*connect.Response[v1.TriggerFunctionResponse], error) {
	return c.triggerFunction.CallUnary(ctx, req)
}

// CheckHealth calls compute.v1.ComputeService.CheckHealth.
func (c *computeServiceClient) CheckHealth(ctx context.Context, req *connect.Request[v1.CheckHealthRequest]) (*connect.Response[v1.CheckHealthResponse], error) {
	return c.checkHealth.CallUnary(ctx, req)
}

// ComputeServiceHandler is an implementation of the compute.v1.ComputeService service.
type ComputeServiceHandler interface {
	RunService(context.Context, *connect.Request[v1.RunServiceRequest]) (*connect.Response[v1.RunServiceResponse], error)
	TriggerFunction(context.Context, *connect.Request[v1.TriggerFunctionRequest]) (*connect.Response[v1.TriggerFunctionResponse], error)
	CheckHealth(context.Context, *connect.Request[v1.CheckHealthRequest]) (*connect.Response[v1.CheckHealthResponse], error)
}

// NewComputeServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewComputeServiceHandler(svc ComputeServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	computeServiceMethods := v1.File_compute_v1_compute_proto.Services().ByName("ComputeService").Methods()
	computeServiceRunServiceHandler := connect.NewUnaryHandler(
		ComputeServiceRunServiceProcedure,
		svc.RunService,
		connect.WithSchema(computeServiceMethods.ByName("RunService")),
		connect.WithHandlerOptions(opts...),
	)
	computeServiceTriggerFunctionHandler := connect.NewUnaryHandler(
		ComputeServiceTriggerFunctionProcedure,
		svc.TriggerFunction,
		connect.WithSchema(computeServiceMethods.ByName("TriggerFunction")),
		connect.WithHandlerOptions(opts...),
	)
	computeServiceCheckHealthHandler := connect.NewUnaryHandler(
		ComputeServiceCheckHealthProcedure,
		svc.CheckHealth,
		connect.WithSchema(computeServiceMethods.ByName("CheckHealth")),
		connect.WithHandlerOptions(opts...),
	)
	return "/compute.v1.ComputeService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ComputeServiceRunServiceProcedure:
			computeServiceRunServiceHandler.ServeHTTP(w, r)
		case ComputeServiceTriggerFunctionProcedure:
			computeServiceTriggerFunctionHandler.ServeHTTP(w, r)
		case ComputeServiceCheckHealthProcedure:
			computeServiceCheckHealthHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedComputeServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedComputeServiceHandler struct{}

func (UnimplementedComputeServiceHandler) RunService(context.Context, *connect.Request[v1.RunServiceRequest]) (*connect.Response[v1.RunServiceResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("compute.v1.ComputeService.RunService is not implemented"))
}

func (UnimplementedComputeServiceHandler) TriggerFunction(context.Context, *connect.Request[v1.TriggerFunctionRequest]) (*connect.Response[v1.TriggerFunctionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("compute.v1.ComputeService.TriggerFunction is not implemented"))
}

func (UnimplementedComputeServiceHandler) CheckHealth(context.Context, *connect.Request[v1.CheckHealthRequest]) (*connect.Response[v1.CheckHealthResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("compute.v1.ComputeService.CheckHealth is not implemented"))
}
